[Feature/230] 나모 V2 도메인 매핑
Namo-Mongmong/Server pull request #245
Opened 2024-08-09 12:06 UTC by hosung-222

## Type of change

- [X] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## PR Desciption

> 변경 사항 설명

- V2 버전 도메인 매핑

## Requirements for Reviewer
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

- User라는 인터페이스로 회원과 비회원을 관리할 수 있도록 할 계획인데 어떻게 생각하시나요?

+
- 각 속성의 타입이나 매핑 관계 꼼꼼히 확인 부탁드립니다.
- 휴먼 오류 확인 부탁드립니다.

## PR Log

> PR 작업하면서 고민했던 내용, 해결한 내용, 고민 중인 내용 등

### 새롭게 배운 것

- 

### 고민 중인 사항

-

## 첨부 자료

-

## 관련 이슈

- close #230

2024-08-09 12:29 UTC, joowojr requested changes

2024-08-09 12:29 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Member.java
닉네임 컬럼이 추가되어야 합니다!

2024-08-09 12:29 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Member.java
> 	@OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
> 	private Set<Friendship> friendships = new HashSet<>();

member로 매핑되어야 합니다

2024-08-09 12:29 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Participants.java
>	@JoinColumn(name = "user_id")
>	private Member member;

member_id로 수정해야할거 같습니다!

2024-08-09 12:29 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Participants.java
participants 보다는 participant의 의미가 더 맞을거 같습니다.

2024-08-09 12:29 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/oauth/entity/Oauth.java
>@Builder
>	public Oauth(Provider provider, String providerId, String loginId, String socialRefreshToken, Member user) {

빌더 인자 부분에 member로 바꿔주시면 좋을거 같습니다!

2024-08-09 12:40 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Anonymous.java
익명 유저가 user를 상속받는 이유가 있을까요?

2024-08-09 15:25 UTC, joowojr requested changes
participant 엔티티 네이밍 바뀌면서 인자명에 대한 전체적인 수정이 필요해보입니다!

2024-08-09 15:25 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Anonymous.java
- name과 nickname의 column명이 중복됩니다!
- 빌더에 필요 없는 인자들 제거해주세요!

2024-08-09 15:25 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Member.java
- name과 nickname의 column명이 중복됩니다
- 프로필 이미지 컬럼 필요합니다!
- > @SQLDelete(sql = "UPDATE members SET deleted_at = NOW(), status = 'INACVTIVE' WHERE id = ?")

  members -> member 수정 필요합니다!

2024-08-09 15:25 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Participant.java
> @Table(name = "participants")

테이블 명도 변경해주세요!

>	@JoinColumn(name = "schedule_id", nullable = false)
>	private Category category;

column명 변경해주세요!

2024-08-09 15:25 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/entity/DiaryImage.java
> @Table(name = "diary_img")
이름 통일해주면 좋을거 같아요

2024-08-09 15:25 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/entity/Diary.java
>	@ManyToOne(fetch = FetchType.LAZY, optional = false)
>	@JoinColumn(name = "participants_id", nullable = false)
>	private Participant participants;

participants 수정 부탁드려요!

2024-08-09 15:25 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/entity/ActivityParticipants.java
>@Table(name = "activity_participants")
>@NoArgsConstructor(access = AccessLevel.PROTECTED)
>@DynamicInsert
>public class ActivityParticipants extends BaseTimeEntity {

participants 수정 부탁드려요!

2024-08-09 15:25 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/entity/ActivityImage.java
> public void updateImgOrder(Integer imageOrder) {

Img -> Image로 수정 부탁드려요!

2024-08-09 15:25 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/entity/Diary.java
빌더도 추가 부탁드려요!

2024-08-09 15:25 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Term.java
> public Term(Member user, String content, boolean agree, LocalDateTime agreeAt) {

Member 인자명 변경해주세요!

2024-08-09 15:25 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/category/entity/Category.java
> @Builder
>	public Category(Member user, Palette palette, String name, CategoryStatus status, CategoryType type,
>		Integer order)

Member 인자명 변경 필요합니다!

2024-08-09 15:25 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/category/entity/Category.java
>@Column(name = "order_num", nullable = false)
>	private Integer order;

order_number로 통일해도 좋을거 같아요!

2024-08-09 15:25 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/common/converter/UserStatusConverter.java
MemberStatusConverter로 수정해야합니다!

2024-08-09 15:25 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/common/converter/UserRoleConverter.java
MemberRoleConverter로 수정해야합니다!

2024-08-09 15:25 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/alarm/entity/Device.java
member column 필요합니다!

2024-08-09 15:25 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/service/ActivityService.java
>	@Transactional(readOnly = true)
>	public List<Activity> raedActivityListByMeetingScheduleId(Long meetingScheduleId) {
>		return null;
>	}

read 오타 수정, meeting 삭제, 리턴 값 필요합니다!

2024-08-09 15:29 UTC, joowojr requested changes

2024-08-09 15:29 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/alarm/type/PublisherType.java
> USER("1", "사용자")

MEMBER로 통일하는 것 어떨까요?

2024-08-09 15:44 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/type/FriendshipStatus.java
구체화 필요해보입니다.
+) NotificationType과 통일해서 DECLINED -> REJECTED 변경은 어떨까요?

2024-08-09 15:44 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Friendship.java
status에 대한 set 메서드도 추가하면 좋을거 같아요!

2024-08-09 15:44 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/user/entity/Member.java
status에 대한 set 메서드도 추가하면 좋을거 같아요!

2024-08-09 15:44 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/schedule/entity/Schedule.java
초대 기능에 대한 code 또는 url 컬럼명 필요해보입니다!
와이어프레임 보면 기존 친구도 code를 통해 초대가 가능한거 같은데, 이 부분에 대해 확인하고 수정하면 좋을거 같아요.

2024-08-10 08:52 UTC, hosung-222 commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/alarm/entity/Device.java
member Coloum이 device에 필요한가요? Notification에 member와 연결 되어있는 상태 아닌가요?

2024-08-10 08:52 UTC, hosung-222 commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/service/ActivityService.java
엔티티 매핑만 이루어졌고 서비스로직이나 기타로직은 개발하면서 수정이 필요합니다. 기존에 통으로 옮겨오면서 변경이 안된 항목이 많습니다

2024-08-10 13:02 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/service/ActivityService.java
확인입니다!

> 엔티티 매핑만 이루어졌고 서비스로직이나 기타로직은 개발하면서 수정이 필요합니다. 기존에 통으로 옮겨오면서 변경이 안된 항목이 많습니다

2024-08-12 02:55 UTC, joowojr approved these changes
수고 많으셨습니다👏🏻

2024-08-12 02:55 UTC, joowojr commented on storage/db-mysql-v2/src/main/java/com/namo/spring/db/mysql/domains/record/entity/Activity.java
재미도, 카테고리 컬럼 필요합니다
<img width="262" alt="image" src="https://github.com/user-attachments/assets/c0f5dfc4-f3b0-433d-8565-8efc79dc1614">

2024-08-12 04:36 UTC, merged